<?php 
return [
 'config_meta_tag_keywords' => 'otrixcommerce,ecommerce'  ,
 'config_fb_url' => 'https://www.facebook.com/'  ,
 'config_linkedin_url' => 'https://www.linkedin.com/'  ,
 'config_twitter_url' => 'https://twitter.com/login?lang=en'  ,
 'config_youtube_url' => 'https://www.youtube.com/channel/UCiWzLziMAOk-oB0pig8TkEg/'  ,
 'config_mail_engine' => 'smtp'  ,
 'config_insta_url' => 'https://www.instagram.com/'  ,
 'config_smtp_username' => 'otrixapp@gmail.in'  ,
 'config_smtp_hostname' => 'smtp.googlemail.ddd'  ,
 'config_smtp_password' => 'abcdabcdefgefg'  ,
 'config_smtp_timeout' => '25'  ,
 'config_smtp_port' => '25'  ,
 'config_store_image' => '1734337779logo.png'  ,
 'config_alert_mail' => 'Register,Orders'  ,
 'config_icon_image' => '168941197910.png'  ,
 'config_currency' => '$'  ,
 'config_fax' => '380001'  ,
 'config_telephone' => '09898989898'  ,
 'config_email' => 'otrixapp@gmail.in'  ,
 'config_geocode' => '54654'  ,
 'config_store_owner' => 'Admin'  ,
 'config_address' => 'Building Number 121
Ground floor, Office 2'  ,
 'config_store_name' => 'Detayler'  ,
 'config_meta_tag_description' => 'OtrixCommerce is your go-to destination for all your online shopping needs. Our ecommerce website offers an extensive collection of high-quality products at competitive prices, ranging from fashion and beauty to electronics and home essentials.
        Our user-friendly interface and fast-loading pages provide a seamless shopping experience for customers. We have optimized our website for search engines to ensure that our products are easily discoverable by potential customers.
        We prioritize customer satisfaction and have a dedicated customer support team available to assist you with any inquiries or concerns. With a secure payment gateway and fast shipping, we strive to make online shopping stress-free and convenient.
        At OtrixCommerce, we are committed to providing you with the best online shopping experience possible. Browse our extensive collection today and discover something new!'  ,
 'config_meta_title' => 'Otrixcommerce Website'  ,
 'config_web_bg' => '#626ABB'  ,
 'config_currency' => '$'  ,
 'config_fax' => '380001'  ,
 'config_telephone' => '09898989898'  ,
 'config_email' => 'otrixapp@gmail.in'  ,
 'config_geocode' => '54654'  ,
 'config_address' => 'Building Number 121
Ground floor, Office 2'  ,
 'config_store_owner' => 'Admin'  ,
 'config_store_name' => 'Detayler'  ,
 'config_encryption' => 'tls'  ,
 'config_from' => 'otrix@mail.in'  ,
 'config_from_name' => 'dasd'  ,
 'config_signup_discount_status' => '1'  ,
 'config_signup_discount' => '15'  ,
  "config_signup_discount_text" =>  "{\"4\":\"Sign Up  And  _DISCOUNT_  special discount on your first order\",\"5\":\"\\u0627\\u0634\\u062a\\u0631\\u0643 \\u0648 _DISCOUNT_ \\u062e\\u0635\\u0645 \\u062e\\u0627\\u0635 \\u0639\\u0644\\u0649 \\u0637\\u0644\\u0628\\u0643 \\u0627\\u0644\\u0623\\u0648\\u0644\"}",  'config_layout' => 'otrixlayout'  ,
 'config_twilio_sid' => 'AC03edc552fb'  ,
 'config_twilio_token' => '721bd6d11442ced'  ,
 'config_twilio_from' => '+17622'  ,
 'config_alert_sms' => 'Register,Orders'  ,
 'config_registerSMSContent' => 'Thank you for register on otrixcommerce'  ,
 'config_talk_to_expert' => '{\"4\":\"Hello\",\"5\":\"\\u0645\\u0631\\u062d\\u0628\\u064b\\u0627\"}'  ,
  "config_talk_to_expert" =>  "{\"4\":\"Hello\",\"5\":\"\\u0645\\u0631\\u062d\\u0628\\u064b\\u0627\"}",  'config_talk_to_expert_mobile' => '+9198256'  ,
 'config_social_status' => '1'  ,
 'config_accept_terms_before_order' => '1'  ,
];
